const types = {
  
    // -- PLANETS -- //
    GET_PLANETS_START: 'GET_PLANETS_START',
    GET_PLANETS_SUCCESS: 'GET_PLANETS_SUCCESS',
    GET_PLANETS_FAILURE: 'GET_PLANETS_FAILURE',

    GET_MORE_PLANETS_START: 'GET_MORE_PLANETS_START',
    GET_MORE_PLANETS_SUCCESS: 'GET_MORE_PLANETS_SUCCESS',
    GET_MORE_PLANETS_FAILURE: 'GET_MORE_PLANETS_FAILURE',

    // -- SINGLE_PLANET -- //
    GET_SINGLE_PLANET_START: 'GET_SINGLE_PLANET_START',
    GET_SINGLE_PLANET_SUCCESS: 'GET_SINGLE_PLANET_SUCCESS',
    GET_SINGLE_PLANET_FAILURE: 'GET_SINGLE_PLANET_FAILURE',
    
  };
  
  export default types;
  